#[derive(Debug, PartialEq, Eq, Clone, Hash)]
pub enum DataTypes {
    Int,
    Float,
    Bool,
    Colour,
}

#[derive(Debug, PartialEq, Hash, Eq, Clone)]
pub enum TokenKind {
    Whitespace,
    Invalid,
    Newline,
    LBrace,
    RBrace,
    Equals,
    EqEq,
    LParen,
    RParen,
    LBracket,
    Semicolon,
    RBracket,
    Identifier(String),
    // Keywords
    For,
    If,
    Else,
    While,
    Function,
    Let,
    PadWidth,
    PadHeight,
    PadRead,
    PadRandI,
    Print,
    Delay,
    Return,
    // Binary operators
    Multiply,
    Divide,
    And,
    Plus,
    Minus,
    Or,
    // Relational operators
    LessThan,
    LessThanEqual,
    GreaterThan,
    GreaterThanEqual,
    Equal,
    NotEqual,
    // Types
    Type(DataTypes),
    // Type literals
    IntLiteral(i32),
    FloatLiteral(String),
    BoolLiteral(bool),
    ColourLiteral(String),
    EndOfFile,
    Colon,
    Comment,
    Asterisk,
    DoubleQuote,
    Comma,
    Hashtag,
    PadWrite,
    PadWriteBox,
    As,
}
